sudo: required
services:
  - docker

before_install:
  - docker build -t danielefrisanco/docker-react -f Dockerfile.dev .

script:
  - docker run danielefrisanco/docker-react npm run test -- --coverage